### ISSUE TITLE
Paypal not working on ios xcode 6

### ISSUE THREAD

**Issue by mauricioaguirre** [paypal/PayPal-Cordova-Plugin#100]
Hi,

We used the paypal gateway on ios. However is not working. At the time we click on the button it does nothing. 

Can you help us out, please?

Thanks

Mauricio Aguirre

**Comment by jaypatel512** [comment]
Hey @mauricioaguirre !

I used the [sample app](https://github.com/paypal/PayPal-Cordova-Plugin#basic-example-of-the-app) that demonstrates the behavior, and updated the mode to Sandbox, by changing the [onRender arguments](https://github.com/romk1n/MyCordovaShop/blob/master/www/js/index.js#L113), and I was able to successfully build and run ios simulator.

I am using XCode 6.4

**Comment by jaypatel512** [comment]
Can you please try running the sample app and see if the issue is visible there too. This will eliminate if something is wrong on plugin or your setup.

**Comment by mauricioaguirre** [comment]
Thanks for your quick response and help!!!

I implemented this plugin phonegap, creating it for both platforms (android / ios) the current plug-in  works perfectly in android for me, but my issue is only in IOS.

The solution that you gave me. that i already tried is not working, also I added the "config.xml" the following line "<gap: plugin name =" com.paypal.cordova.mobilesdk "version =" 3.1.6 "source = "npm" /> " however is still not working.

The only issue is that when you press the button to process the payment, nothing happens, not even an error appears on the console.

I attached a screenshot and part of my code.

http://bit.ly/1NFrHFt

JS PAYPAL

'use strict';

angular.module("arseneAngularApp")
	.factory("StoreLocalSvc", function(){
		function get(){
			var setting = {
				"currency" : "MXN",
				"logo" : "assets/images/logo.jpg",
				"name" : "Arsene Store",

				"viewsUrl" : "app/app-pages",

                "payPalSandbox" : "ARxHMZXLXHJxRbkuqxuwTonzc4NGuQf7FMBGgZo_2Btxzihh27FbUfNiK_E71JT3GMiHv6vyAFs_wzqq",
                "payPalProduction" : "YOUR_PRODUCTION_CLIENT_ID"
			}
			return setting; 
		}
		function ui(){
			var ui = {
				"pageEffect" : "fade"
			}
			return ui; 
		}
		return {
		    get : get,
		    ui : ui
		};
	});

JS BUTTON
$scope.pay = function(){
		$scope.order.customer_note = "Optional";
		$scope.validateOrder = UtilsSvc.formValidation($scope.order);
		//JUST FOR TEST
		try{
			if($scope.validateOrder.validateAll == true)
				PayPalMobile.renderSinglePaymentUI(PaypalSvc.createPayment($scope.order.total_amount), onSuccesfulPayment, onUserCanceled);	
		}
		catch(err){
		}
	}
	
	if(typeof PayPalMobile != 'undefined')
		PaypalSvc.initPaymentUI();
	page_load();
  });
  
HTML BUTTON
span class="btn-default col" ng-click="pay()">Pay with PayPal</span

**Comment by jaypatel512** [comment]
Are you sure, when doing initPaymentUI, you are passing the clientIds properly ? 
```
initPaymentUI : function () {
     var clientIDs = {
       "PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
       "PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
     };
     PayPalMobile.init(clientIDs, app.onPayPalMobileInit);

   },
```

**Comment by mauricioaguirre** [comment]
Still does not work Could you be a little more specific please, in the name of the function or calling that I need to add?

When i added the above code the app simply did not start

Thanks!!!

**Comment by jaypatel512** [comment]
Btw, as per your comments, even the sample app is not working right ? We can probably focus on that. Do you have any logs related to the sample app ? The reason I am asking you to test sample app, is it gives me the ability to help you better, as I understand it works perfectly in other systems.

**Comment by odzero** [comment]
Hi Jay, I'm friends with Mauricio Aguirre, and I'm trying to solve the problem with him.

The problem we have is that we do not have much support the sample app, because we bought via the Internet and the creator does not know the cause of the problem either, it says that is because our configuration xcode, but we do not think so .

Xcode does not show any errors, and we have already unsuccessfully tried every recommendation.

I was wondering if it is possible to send you the entire project in a zip and could help us figure out the problem, I really appreciate it, we have several days searching the error.

**Comment by jaypatel512** [comment]
Hey @odzero ! 

If you have basic understandings about github, you should be able to download the project, by following the instructions here. https://github.com/romk1n/MyCordovaShop

Because it requires you to install npm, and cordova in your computer, it is not easy to just zip the project. 

Just follow the instructions provided in the [README.md](https://github.com/romk1n/MyCordovaShop/blob/master/README.md) here, and you should be easily able to setup the ios. If the sample app works for you, then the problem is in the app that you bought. If you still are facing the issue on sample app, then it could potentially be Plugin or your XCode setup. 

Also, it is always good to update to the latest version of XCode.

**Comment by romk1n** [comment]
It maybe also useful to have a look at this issue since you using angular https://github.com/paypal/PayPal-Cordova-Plugin/issues/61

**Comment by bluk** [comment]
The Cordova plugin 3.1.16 has been updated with the latest PayPal iOS SDK 2.12.5 which contains various fixes. Please reopen if this is still an issue.

**Comment by nguyenkhanh87** [comment]
I am using cordova 6.1.1 and  paypalmobile 3.1.25
I got same issue like @mauricioaguirre
