### ISSUE TITLE
INSTRUMENT_DECLINED

### ISSUE THREAD

**Issue by igordeoliveirasa** [paypal/PayPal-Cordova-Plugin#109]
Hi, I'm always receiving the following error when I tap Pay:

PayPal SDK: Request has failed with error: INSTRUMENT_DECLINED - Your selected payment method was not accepted. Please choose a different method. (400) | PayPal Debug-ID: 96bcb4b90efae [live, PayPal iOS SDK 2.11.3]

Please, is anybody able to help me?

**Comment by tomwhipple** [comment]
This happens when the underlying funding instrument in your PayPal account declines the transaction for some reason. For example, your credit card is expired or the card declines the payment.

Since this is an account specific problem and not a bug in the Cordova plugin, you'll need to work with [PayPal Merchant Support](https://www.paypal-techsupport.com/app/ask) or your bank to figure out the problem.

**Comment by igordeoliveirasa** [comment]
Tom, I don't think so. Since I'm used to buy frequently with this credit card and paypal account. Do you have any other tip?

**Comment by jaypatel512** [comment]
I think at this point the PayPal Merchant Support would be able to help you with that. As @tomwhipple mentioned before, the issue is not with the plugin, but with paypal account in question.

**Comment by igordeoliveirasa** [comment]
Jay and Tom, I've tryied with multiple good paypal accounts here... And the return is the same for all of them. Any tip?
