### ISSUE TITLE
Credit Card user being charged multiple times

### ISSUE THREAD

**Issue by Vincenttbk** [paypal/PayPal-Cordova-Plugin#132]
Hi,

I've rolled out my app recently, and I have complains of users being charged multiple times on their credit card. 

They paid using direct credit card feature.

Would want to find out if anyone encounter this issue?

Thanks

Regards
Vincent

**Comment by ppmtscory** [comment]
@Vincenttbk can you please provide a couple of Sale ID's for the duplicates?

**Comment by Vincenttbk** [comment]
How do i get the Sales ID?

**Comment by ppmtscory** [comment]
It would be your transaction ID of the payment that went into your account.

**Comment by Vincenttbk** [comment]
Hi, is it safe to post the transaction ID here? is there a way to private message? THanks :)

**Comment by ppmtscory** [comment]
Yes, you can paste the transaction ID here, that's fine.  Otherwise, if you don't feel comfortable, you can always file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to work with an agent directly.  Just be sure to include your account email address, transaction example, and reference to this GitHub issue in your ticket.

**Comment by bluk** [comment]
Closing this issue due to it seeming to be resolved via Merchant Tech Support. If not, please leave a comment.
