### ISSUE TITLE
Amount not deducted from buyer account

### ISSUE THREAD

**Issue by vikas0vanvi** [paypal/PayPal-Cordova-Plugin#167]
after adding this plugin its adding amount to merchant sandbox account but money is not deducted from buyer sandbox account , in recent activities of buyer account its showing deduction of amount like -100$ but total remaining same and its showing success response too  , what could be wrong ?

![capture](https://cloud.githubusercontent.com/assets/16686166/14040752/840e27f4-f290-11e5-9691-2f92e81c54bd.PNG)

**Comment by pp-randy** [comment]
This shows an authorization was made, so that would need to be captured.  Both Authorization and Order require additional API calls to complete payments.  Sale might be what you are looking for.  Try setting your intent to sale if you are using code similar to this below. 

https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/android/PayPalMobileCordovaPlugin.java#L149

```
String intentString = paymentObject.getString("intent");

String paymentIntent = null;
if ("sale".equalsIgnoreCase(intentString)) {
	paymentIntent = PayPalPayment.PAYMENT_INTENT_SALE;
} else if ("order".equalsIgnoreCase(intentString)) {
	paymentIntent = PayPalPayment.PAYMENT_INTENT_ORDER;
} else {
	paymentIntent = PayPalPayment.PAYMENT_INTENT_AUTHORIZE;
}
```

Here is more about authorizations as well https://developer.paypal.com/docs/integration/direct/capture-payment/

**Comment by pp-randy** [comment]
Closing this issue.  Please let me know if you need more information.
