### ISSUE TITLE
Paypal - payment cant go through

### ISSUE THREAD

**Issue by leoo232** [paypal/PayPal-Cordova-Plugin#169]
Hi guyz,

I have a question concerning paypal - i have done everything right and the Paypal plugin in working fine  on Sandbox. but when i use the live credentials- it gives me : The merchant does not accept this type of payment.

I have read that i need a Paypal Pro account. But these account are available only in USA, Canada and UK.. The merchant im dong the app for is in Mauritius.

Anyone has a idea on how i can tackle this issue

Thx in advance

**Comment by bluk** [comment]
If you want to use only PayPal payments, please ensure that you have the correct permissions on the [Developer Dashboard Account Status page](https://developer.paypal.com/developer/accountStatus/). PayPal payments is required. If you have this enabled but you still have issues, I suggest you contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) with your merchant information so they can look into your account and determine what the issue is.

If you are using direct credit cards, then there is unfortunately not much that can be done. Direct credit card support is more limited to US/UK Pro accounts at this time.
