### ISSUE TITLE
onSuccesfulPayment callback not called

### ISSUE THREAD

**Issue by janeandroid** [paypal/PayPal-Cordova-Plugin#173]
I have added below function in Paypal.js file...

onSuccesfulPayment: function(payment) {
  
	alert("onSuccesfulPayment");
	
	localStorage.payPal = "payment success: " + JSON.stringify(payment, null, 4);
    console.log("payment success: " + JSON.stringify(payment, null, 4));
	
	if(payment["response"]["state"] == "approved") {
		var paidAmt=$("#memAmount"+app.pay_membership_id).val();
		var payId = payment["response"]["id"];
	}
	else {
		alert("Payment could not be completed successfully.");
	}
  }
PayPalMobile.renderSinglePaymentUI(app.createPayment(), app.onSuccesfulPayment, app.onUserCanceled);

But, onSuccesfulPayment is not called.

I see Paypal screen and can even login to the Paypal, but after logged in I do not see next screens.

I am not sure what values should we set in below lines

 var clientIDs = {
       "PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
       "PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
    };

**Comment by bluk** [comment]
Are you in the No Network / Mock flow? For the `My Cordova Shop` example, it is [setup to be the NoNetwork flow by default](https://github.com/romk1n/MyCordovaShop/blob/master/www/js/index.js#L113). Use `PayPalEnvironmentSandbox` instead of `PayPalEnvironmentNoNetwork` for testing your app.

```
var clientIDs = {
"PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
"PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
};
```

For the client IDs, you need to create an application on the [PayPal Developer website](https://developer.paypal.com/). Login, and then click the [My Apps and Credentials](https://developer.paypal.com/developer/applications/) link. Create an app and then get your sandbox and production client IDs there. You need a value for both, but if you're just testing your app, you can just use the real sandbox client ID there.

The sandbox environment allows you to create your own sandbox PayPal accounts to make sure that you're not using real accounts. You can create them in the developer dashboard.

If you have any additional issues, please leave a comment and we'll reopen, or open a new issue. Thanks.
