### ISSUE TITLE
zh-Hant_HK code does not work

### ISSUE THREAD

**Issue by ghost** [paypal/PayPal-Cordova-Plugin#224]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- Cordova Plugin Version: 3.3.1
- Platforms (iOS/Android/Both): Android
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): Android 5.1.1/6.0.1/7.0.1
- PayPal-Debug-ID(s) (from any logs): 2242d7279eb9

### Issue Description

Using an Android device, attempt to use `zh-Hant_HK` as the value for languageOrLocale results in English localization.  This seems to work fine for iOS devices.

**Comment by bluk** [comment]
Hello,

http://paypal.github.io/PayPal-Android-SDK/com/paypal/android/sdk/payments/PayPalConfiguration.html#languageOrLocale-java.lang.String- has the list of officially supported locales that can be used. The iOS SDK tries to use the native iOS tools to choose the "best" locale for you if it doesn't match which is why it works in one but not the other.

**Comment by alburdette619** [comment]
From paypal-mobile-js-helper:

`    /// These localizations are currently included:
    /// da,de,en,en_AU,en_GB,en_SV,es,es_MX,fr,he,it,ja,ko,nb,nl,pl,pt,pt_BR,ru,sv,tr,zh-Hans,zh-Hant_HK,zh-Hant_TW.
    languageOrLocale: null,`

This should be updated then as zh-Hans_HK is listed as included.

**Comment by bluk** [comment]
@alburdette619 Thanks I updated the JavaScript documentation.
