### ISSUE TITLE
Need credt card payment but Disable Card io

### ISSUE THREAD

**Issue by SidharthPHariharan** [paypal/PayPal-Cordova-Plugin#243]
Hello,

I need user to pay using their card but directly over keyboard and should bypass the card io. Is that possible?

I have the credit card but no paypal account and did'nt want to use the card io. I tried disable acceptcreditcard:false but this completely remove the option to use credit card.

Please recommend me a way to bypass the card io.

Regards,
Sidharth

**Comment by ppmtscory** [comment]
@SidharthPHariharan I'm not aware of a way to do this currently.  Perhaps @bluk could confirm for us that this isn't an option at this time?

**Comment by bluk** [comment]
There isn't a way to do direct credit cards without card.io at this time. Also, FYI, the direct credit card option is deprecated in the base [Android](https://github.com/paypal/PayPal-Android-SDK/releases/tag/2.15.0) and [iOS](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.16.0) SDKs at this time.

I would recommend looking at the [Braintree SDKs](https://www.braintreepayments.com) if you want to take credit cards since they support more countries and have more options (without card.io) in their SDKs. Braintree Drop-In is a prebuilt form which is probably what you want.

**Comment by bluk** [comment]
Closing this since with the last comment.
