### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by ds8k** [paypal/PayPal-Cordova-Plugin#246]
### Required Information

- Mode: Live
- Cordova Plugin Version: 3.3.1
- Platforms: iOS
- Device OS Version and Device: iPhone 6+ on iOS 10
- PayPal-Debug-ID(s): 94e7160f52f85, a4736e7e9d46

### Issue Description

Consistently getting this error with one specific client ID:

```
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 94e7160f52f85, 94e7160f52f85 [live, PayPal iOS SDK 2.15.1]

PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a4736e7e9d46, a4736e7e9d46 [live, PayPal iOS SDK 2.15.1]
```

This happens when attempting to sign in to a production PayPal account. Does not happen on Sandbox or on Android.

**Comment by bluk** [comment]
Is the merchant account (payee) denying payments made in a different currency? It seems that the payment is being made in a currency that the merchant does not accept.

Are you using the same merchant client ID for both iOS and Android and using the same customer account to pay with?

**Comment by ds8k** [comment]
@bluk Yes, same client ID and same account. I didn't go through with the purchase on Android, but I was able to sign in with my production account. On iOS I'm not able to sign in.

**Comment by bluk** [comment]
There is a difference in the flows between Android and iOS versions of the SDK due to the native code differences. You may encounter this same error on the Android side if you proceeded with the purchase.

I would look into the customer account and verify that the funding instrument currency is accepted by the merchant account.

If that does seem correct, another way to double check though is to login to your Merchant Account on www.paypal.com . Click on `Profile > Profile and settings > My selling tools > Click Update in the Block Payments section (under Getting paid and managing my risk)`. Then change the `Allow payments sent to me in a currency I do not hold`. Note that additional charges apply to do the conversion. You can then test if you can login on iOS.

<img width="771" alt="screen shot 2016-11-28 at 12 07 57 pm" src="https://cloud.githubusercontent.com/assets/94150/20680185/9fa1d1f0-b563-11e6-8e00-16242005a7fa.png">

**Comment by ds8k** [comment]
Ah okay, I hadn't considered the different flows. Thank you, I'll look into this further!
