### ISSUE TITLE
Remove cancel button on ios

### ISSUE THREAD

**Issue by dhameer** [paypal/PayPal-Cordova-Plugin#247]
### Required Information

- Mode (Mock/Sandbox/Live): live
- Cordova Plugin Version: 2.0.1
- Platforms (iOS/Android/Both): ios
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): iPhone (all)

### Issue Description

Hi 

I am trying to remove the cancel button from the paypal plugin(on android I can programmatically disable the back button)

On IOS there is a cancel button which I am trying to remove. Is this possible?

**Comment by bluk** [comment]
Which cancel button are you referring to? Can you please post a screenshot?

**Comment by dhameer** [comment]
Thanks for your reply, it is this one(see screenshot). "Cancel on top left".
![screen shot 2016-11-30 at 5 46 19 am](https://cloud.githubusercontent.com/assets/16570601/20739074/766b64dc-b6c0-11e6-97b2-73e0b1970c61.png)

**Comment by bluk** [comment]
The `Cancel` button is there to cancel out of the payment flow in case the user changes his/her mind. There isn't a way to disable it, and I don't think we will provide a way to since we don't want users to be stuck in a flow where the only action is to either pay or to quit the app.

Also, I would advise [seeing if your merchant account is supported for credit card payments](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/?mark=country%20support) using this SDK. This SDK uses the PayPal REST API which does not officially support direct credit cards from non-UK Pro accounts right now.
