### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by subhash8108** [paypal/PayPal-Cordova-Plugin#251]
Hello,

When install your plugin after run cordova android project, then get the gradle error. you can see below screen short.

![gradle-error](https://cloud.githubusercontent.com/assets/542535/21229738/97246ee0-c308-11e6-9423-5f0047c8f75e.png)

Please help me

Thanks
Subhash Patel

**Comment by bluk** [comment]
Your Android project must require a minimum version of Android SDK version 16 as the Gradle error states. Basically, the PayPal Android library requires Android SDK version 16 due to TLS 1.2 requirements (see https://github.com/paypal/TLS-update#android-requirements ). You should be able to change your Android project's minimum SDK requirement.
