### ISSUE TITLE
Shipping amount not show in total amount charge

### ISSUE THREAD

**Issue by mahesh-vi** [paypal/PayPal-Cordova-Plugin#298]
I use following code for Paypal payment detail.
 
var paymentDetails = new PayPalPaymentDetails("13.0", "5.00", "0.00");

But when paypal plugin load it shows only "13.0" amount in charges and "Payment Failed - Payment Information is invalid" alert display. 

When I use  following code then it work fine for me.

var paymentDetails = new PayPalPaymentDetails("13.0", "0.00", "0.00");

So Please suggest me to how to calculate shipping charges using paypal plugin.

**Comment by mahesh-vi** [comment]
Resolve this issue from issue #7

**Comment by pp-randy** [comment]
If you have only started development, you should consider message at the top of the [README](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/README.md) and review some of the other offerings since Mobile SDKs are deprecated.  

**Important**: PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.
