### ISSUE TITLE
Android version not working with payment.items

### ISSUE THREAD

**Issue by jsappme** [paypal/PayPal-Cordova-Plugin#96]
When I add payment.items to my Paypal payment, Paypal does not let me pay giving me an error saying "The payment information is invalid...". 

Here is my Paypal payment object:
 getPaypalItems: {"amount":"45","currency":"USD","shortDescription":"Total...","intent":"Sale","details":{"subtotal":"45","shipping":"0.00","tax":"0.00"},"invoiceNumber":"kOnETFRn0t","items":[{"name":"Candy Bikini Top","quantity":1,"price":"45","currency":"USD","sku":""}]}

It's working great with iOS and if I remove payment.items it will work fine with Android but I need the payment details. Am I missing something?

**Comment by romk1n** [comment]
@jsappme  i have managed to reproduce the problem. if you look in the console you should see a message like this:

```
E/paypal.sdk( 2288): request failed with server response:{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].item_list.items[0].sku","issue":"Must not be blank"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"69607b31ff623"}
```

the problem is that `sku` is empty string and neither the sdk nor the [wrapper](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/android/PayPalMobileCordovaPlugin.java#L355) on Android deals with it correctly.

The simple workaround is to pass `null` rather then `""` if you don't use `sku`.

**Comment by jsappme** [comment]
Wouahh Romk1n you're the best. Issue fixed by setting sku to null. Thanks.
